# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'

# Permalinks
permalink:        pretty

# Setup
title:            Engineering blog by Mikołaj Kania
description:      "<a href='https://pl.linkedin.com/in/mikolajkania' target='_blank'><b>Mikołaj Kania</b></a> <br/> Technical Program Manager, Team Lead, Software Engineer who blogs about machine learning, search engines and software development. Let's stay in touch!"
linkedin:		  http://www.linkedin.com/in/mikolajkania/
twitter:		  https://twitter.com/MikolajKania
medium:           https://medium.com/@mikolajkania
url:              mikolajkania.com
rss:              http://mikolajkania.com/atom.xml

author:
  name:           'Mikołaj Kania'
  url:            https://pl.linkedin.com/in/mikolajkania

paginate:         7

excerpt_separator: <!--excerpt-->

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/mikolajkania

plugins: [jekyll-paginate]
