# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            itblues.pl
tagline:          'Programming blog by Mikołaj Kania'
description:      'Programming blog by <a href="https://pl.linkedin.com/in/mikolajkania" target="_blank">Mikołaj Kania</a>.'
linkedin:		  https://pl.linkedin.com/in/mikolajkania
twitter:		  https://twitter.com/mikolajkania
url:              itblues.pl
baseurl:          /

author:
  name:           'Mikołaj Kania'
  url:            https://pl.linkedin.com/in/mikolajkania

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/mikolajkania

gems: [jekyll-paginate]