# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            IT Blues
tagline:          'Software engineer\'s blog'
description:      'Software engineer\'s blog by Mikolaj Kania'
url:              http://itblues.pl
baseurl:          /

author:
  name:           'Mikolaj Kania'
  url:            https://twitter.com/oficjalny

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
