# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            itblues.pl
tagline:          'Programming blog by Mikołaj Kania'
description:      'Programming blog by <a href="https://pl.linkedin.com/in/mikolajkania" target="_blank">Mikołaj Kania</a>.'
linkedin:		  http://www.linkedin.com/in/mikolajkania/
twitter:		  https://twitter.com/MikolajKania
medium:           https://medium.com/@mikolajkania
url:              itblues.pl
rss:              http://itblues.pl/atom.xml

author:
  name:           'Mikołaj Kania'
  url:            https://pl.linkedin.com/in/mikolajkania

paginate:         6

excerpt_separator: <!--excerpt-->

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/mikolajkania

plugins: [jekyll-paginate]
